"""Hand-written synthetic content for the fictional Northwind Marketplace.

Everything here is invented for the demo. Northwind Marketplace is a made-up
B2B procurement portal where buyer organisations purchase from registered
sellers. No real organisation, person, policy or document is described.

Each branch tuple:
    (branch_id, branch_name, trigger_keywords, agent_script, steps, documents,
     benchmark_queries)
"""

from __future__ import annotations

PORTAL = "Northwind Marketplace"

# ---------------------------------------------------------------------------
# Seller side
# ---------------------------------------------------------------------------

SELLER_CATEGORIES = [
    # (id, display name, escalation team, escalation role)
    ("registration", "Seller Registration", "Vendor Onboarding Desk", "Onboarding Specialist (Tier 2)"),
    ("login_otp", "Login & OTP", "Access Support Team", "Identity Support Analyst"),
    ("profile_kyc", "Profile & KYC", "Vendor Compliance Desk", "Compliance Reviewer"),
    ("bank_payouts", "Bank Account & Payouts", "Seller Finance Desk", "Payout Operations Lead"),
    ("catalogue", "Catalogue & Listings", "Catalogue Quality Team", "Listing Quality Reviewer"),
    ("brand_authorisation", "Brand Authorisation", "Brand Programs Team", "Brand Approval Officer"),
    ("bids_auctions", "Bids & Reverse Auctions", "Sourcing Events Desk", "Bid Support Specialist"),
    ("orders_delivery", "Orders & Delivery", "Order Operations Team", "Fulfilment Coordinator"),
    ("invoices_payments", "Invoices & Payments", "Seller Finance Desk", "Accounts Payable Analyst"),
    ("shipping_logistics", "Shipping & Logistics", "Logistics Partner Desk", "Shipment Exceptions Analyst"),
    ("sub_users", "Sub-users & Roles", "Access Support Team", "Account Administration Analyst"),
    ("disputes_returns", "Disputes & Returns", "Dispute Resolution Cell", "Dispute Case Manager"),
]

SELLER_BRANCHES = {
    "registration": [
        (
            "tax_id_does_not_match_business_name",
            "Tax ID does not match business name during registration",
            ["tax id mismatch", "business name mismatch", "registration validation failed", "tax number not matching", "name mismatch error"],
            "I understand the registration form is rejecting your tax ID. This usually happens when the legal business name differs from the name on the tax certificate. Let's check both together.",
            [
                "Ask the caller to read out the legal business name exactly as printed on the tax certificate.",
                "Compare it with the name entered on the registration form, including punctuation and suffixes such as 'Pvt' or 'LLC'.",
                "If they differ, guide the caller to edit the business name field to match the certificate and resubmit.",
                "If the names already match, ask the caller to clear the browser cache and retry validation once.",
                "If validation still fails, collect a screenshot of the error and escalate.",
            ],
            ["Tax registration certificate", "Screenshot of the validation error"],
            ["registration says tax number does not match company name", "tax id name mismatch while signing up as seller"],
        ),
        (
            "verification_email_link_expired",
            "Verification email link expired",
            ["verification link expired", "activation email", "email link not working", "resend verification", "account activation"],
            "Verification links stay valid for 24 hours. I'll help you request a fresh link so you can finish activating the account.",
            [
                "Confirm the email address the caller registered with.",
                "Ask the caller to open the sign-in page and choose 'Resend verification email'.",
                "Advise them to check spam or quarantine folders and to open the newest email only.",
                "If no email arrives within 15 minutes, verify the address for typos in the admin view and correct it.",
                "Escalate if the address is correct and emails are still not delivered.",
            ],
            ["Registered email address"],
            ["activation link in email has expired", "my email verification link says invalid"],
        ),
        (
            "registration_pending_review",
            "Registration stuck in pending review",
            ["pending review", "registration not approved", "application under review", "waiting for approval", "registration status"],
            "New seller applications are reviewed within three business days. Let me check where yours is in the queue.",
            [
                "Note the registration reference number from the caller.",
                "Check how many business days have passed since submission.",
                "If under three business days, explain the review timeline and set expectations.",
                "If the application is flagged for missing documents, tell the caller which documents to upload.",
                "If it is older than three business days with no flags, escalate for manual review.",
            ],
            ["Registration reference number"],
            ["seller registration is still pending after a week", "application stuck under review status"],
        ),
    ],
    "login_otp": [
        (
            "login_code_sms_not_arriving",
            "Login code SMS not arriving",
            ["otp not received", "one time password", "sms not coming", "login code missing", "verification code"],
            "Sorry you're not receiving the login code. Most delays come from network filters or an outdated mobile number, so let's check both.",
            [
                "Confirm the last four digits of the registered mobile number with the caller.",
                "Ask the caller to wait 60 seconds and use 'Resend OTP' only once to avoid rate limits.",
                "Check whether the number has do-not-disturb or promotional SMS blocking enabled.",
                "Offer the email OTP option if the account has a verified email.",
                "If the registered number is outdated, start the mobile number update process.",
            ],
            ["Registered mobile number"],
            ["not getting the sms code to log in", "otp never arrives on my phone"],
        ),
        (
            "account_locked_after_failed_attempts",
            "Account locked after failed login attempts",
            ["account locked", "too many attempts", "login blocked", "locked out", "temporarily disabled"],
            "For security, accounts lock for 30 minutes after five failed attempts. I can help you get back in safely.",
            [
                "Tell the caller how long remains on the 30-minute lock.",
                "Recommend resetting the password instead of guessing again once the lock lifts.",
                "Verify identity using the registered email and the business reference number.",
                "If the caller needs urgent access, raise an unlock request after identity verification.",
            ],
            ["Business reference number", "Registered email address"],
            ["it says my account is locked", "locked out after entering wrong password many times"],
        ),
        (
            "password_reset_link_not_working",
            "Password reset link not working",
            ["password reset", "forgot password", "reset link invalid", "cannot change password", "reset email"],
            "Password reset links expire after one hour and only the newest link works. Let's send a fresh one.",
            [
                "Ask the caller to request a new reset link from the sign-in page.",
                "Remind them to use only the most recent email, since earlier links are invalidated.",
                "Ask them to open the link in a private browser window to avoid stale sessions.",
                "If the new password is rejected, read out the password rules: 12+ characters with a number and a symbol.",
                "Escalate if the reset page shows an error code.",
            ],
            ["Screenshot of the error, if any"],
            ["forgot password link is not working", "reset password page says token invalid"],
        ),
    ],
    "profile_kyc": [
        (
            "update_registered_business_address",
            "Update registered business address",
            ["change address", "update address", "business address", "office relocation", "address proof"],
            "You can update the registered address from the profile page; the change goes live after a quick document check.",
            [
                "Ask the caller to open Profile > Business details > Address.",
                "Have them enter the new address and upload a supporting address proof dated within the last three months.",
                "Explain that open orders keep their original delivery address.",
                "Tell the caller the compliance review takes up to two business days.",
            ],
            ["Address proof dated within three months"],
            ["we moved office, how do I change the address", "need to update company address on profile"],
        ),
        (
            "kyc_document_rejected",
            "KYC document rejected",
            ["kyc rejected", "document rejected", "verification failed", "identity proof rejected", "upload again"],
            "I'm sorry your KYC document was rejected. The rejection note usually tells us exactly what to fix.",
            [
                "Ask the caller to read the rejection reason shown under Profile > Verification.",
                "If the image was unclear, ask for a colour scan at 300 dpi or higher.",
                "If the document has expired, ask them to upload a currently valid one.",
                "If the name differs from the profile, align the profile name or upload a name-change document.",
                "Escalate if the caller believes the rejection was made in error.",
            ],
            ["Valid identity or business document", "Name-change document, if applicable"],
            ["kyc got rejected what should i upload", "verification document was not accepted"],
        ),
        (
            "change_authorised_signatory",
            "Change authorised signatory",
            ["authorised signatory", "change signatory", "new director", "signing authority", "authorized person"],
            "Changing the authorised signatory needs a board or owner authorisation letter so we can protect your account.",
            [
                "Confirm the caller is currently an admin on the seller account.",
                "Ask them to upload an authorisation letter naming the new signatory.",
                "Have the new signatory complete identity verification from their own login.",
                "Explain that pending bids remain signed by the previous signatory.",
            ],
            ["Authorisation letter on company letterhead", "Identity proof of the new signatory"],
            ["our director changed, need new signing person", "how to replace the authorised signatory"],
        ),
    ],
    "bank_payouts": [
        (
            "payout_bank_account_not_verified",
            "Payout bank account could not be verified",
            ["bank verification failed", "penny drop failed", "account validation", "ifsc", "bank details rejected"],
            "Bank verification fails when the account holder name or routing code doesn't match bank records. Let's check them.",
            [
                "Ask the caller to confirm the account holder name exactly as on the bank statement.",
                "Verify the bank routing code and account number digit by digit.",
                "Ask whether the account is a current account in the business's name; personal accounts are not accepted.",
                "Have the caller re-run verification after correcting the details.",
                "If it fails again, collect a cancelled cheque or bank letter and escalate.",
            ],
            ["Cancelled cheque or bank confirmation letter"],
            ["bank account validation keeps failing", "payout bank details got rejected"],
        ),
        (
            "change_payout_bank_account",
            "Change payout bank account",
            ["change bank account", "update bank", "new bank account", "payout account", "switch bank"],
            "You can change the payout account at any time; payouts pause briefly while the new account is verified.",
            [
                "Confirm the caller is the account admin.",
                "Ask them to add the new account under Finance > Payout accounts.",
                "Explain that a small test credit will verify the account within one business day.",
                "Tell them to set the new account as primary once verified.",
            ],
            ["Cancelled cheque for the new account"],
            ["want to change the bank where payments come", "update payout account details"],
        ),
        (
            "payout_on_hold",
            "Payout on hold",
            ["payout on hold", "payment held", "funds blocked", "settlement hold", "withheld payment"],
            "Payouts are held when there's an open dispute, missing KYC, or an unverified bank account. Let me find which applies.",
            [
                "Check the hold reason shown under Finance > Payouts.",
                "If KYC is incomplete, guide the caller to finish verification.",
                "If a dispute is open, explain that the related amount is released once the dispute closes.",
                "If no reason is shown, escalate with the payout reference.",
            ],
            ["Payout reference number"],
            ["my payment is showing on hold", "why are my settlements blocked"],
        ),
    ],
    "catalogue": [
        (
            "listing_missing_from_buyer_search",
            "Listing missing from buyer search",
            ["product not visible", "listing not showing", "catalogue not visible", "item missing", "not appearing in search"],
            "New listings appear in search after quality review, usually within 24 hours. Let's confirm the listing status.",
            [
                "Ask the caller to open Catalogue > My listings and read the status of the product.",
                "If the status is 'In review', explain the 24-hour review window.",
                "If the status is 'Inactive', ask them to check stock quantity and price validity dates.",
                "If the status is 'Live' but not in search, ask them to search by the exact listing ID.",
                "Escalate with the listing ID if it is live but still not searchable after 24 hours.",
            ],
            ["Listing ID"],
            ["uploaded item is not showing to buyers", "my product is missing from search results"],
        ),
        (
            "listing_rejected_quality_check",
            "Listing rejected in quality check",
            ["listing rejected", "quality check failed", "product rejected", "image rejected", "description issue"],
            "Listings are rejected when images, specifications or pricing don't meet catalogue rules. The rejection note lists the reason.",
            [
                "Ask the caller to read the rejection note on the listing.",
                "For image issues, ask for a plain white background and at least 800x800 pixels.",
                "For specification issues, ensure mandatory attributes such as model and warranty are filled.",
                "For pricing issues, confirm the price is within the allowed range for the category.",
                "Ask the caller to edit and resubmit the listing.",
            ],
            ["Corrected product images", "Product specification sheet"],
            ["product listing failed quality review", "catalogue item got rejected because of images"],
        ),
        (
            "bulk_upload_template_errors",
            "Bulk upload template errors",
            ["bulk upload", "excel template", "csv upload failed", "template error", "mass upload"],
            "Bulk upload errors usually come from an outdated template or a few invalid rows. The error report pinpoints them.",
            [
                "Ask the caller to download the latest template from Catalogue > Bulk upload.",
                "Have them open the error report and fix the rows it lists.",
                "Remind them not to rename columns or change the sheet order.",
                "Ask them to upload no more than 500 rows per file.",
            ],
            ["Error report file", "Filled bulk upload template"],
            ["excel bulk upload keeps throwing errors", "mass product upload template not accepted"],
        ),
    ],
    "brand_authorisation": [
        (
            "brand_approval_pending",
            "Brand approval pending",
            ["brand approval", "brand pending", "brand not approved", "trademark review", "brand registration"],
            "Brand approvals take up to five business days because we verify trademark ownership. Let's check the status.",
            [
                "Note the brand request ID from the caller.",
                "Check whether the request is waiting on a document from the seller.",
                "If complete and under five business days, explain the timeline.",
                "If over five business days, escalate with the brand request ID.",
            ],
            ["Brand request ID", "Trademark certificate"],
            ["brand request still not approved", "how long does brand approval take"],
        ),
        (
            "reseller_authorisation_letter_rejected",
            "Reseller authorisation letter rejected",
            ["authorisation letter", "reseller letter", "dealer certificate", "oem authorization rejected", "distributor letter"],
            "To sell another company's brand, we need a valid authorisation letter from the brand owner. Let's see why it was rejected.",
            [
                "Ask the caller to read the rejection reason.",
                "Confirm the letter is on the brand owner's letterhead and signed.",
                "Check the letter names the seller's legal business name and has a validity date.",
                "Ask the caller to upload the corrected letter.",
            ],
            ["Signed authorisation letter from the brand owner"],
            ["dealer authorization letter was rejected", "reseller certificate not accepted"],
        ),
        (
            "add_new_brand_to_catalogue",
            "Add a new brand to the catalogue",
            ["new brand", "add brand", "brand not in list", "create brand", "brand missing"],
            "If your brand isn't in the dropdown, you can request it. Once approved, it becomes available for your listings.",
            [
                "Ask the caller to search the brand list once more with alternate spellings.",
                "Guide them to Catalogue > Brands > Request new brand.",
                "Have them attach the trademark certificate or brand ownership proof.",
                "Explain the five-business-day review timeline.",
            ],
            ["Trademark certificate or brand ownership proof"],
            ["my brand is not in the dropdown list", "how do I register a new brand name"],
        ),
    ],
    "bids_auctions": [
        (
            "unable_to_submit_bid_before_deadline",
            "Unable to submit bid before deadline",
            ["cannot submit bid", "bid submission failed", "bid deadline", "submit button disabled", "upload bid documents"],
            "Bid submission blocks when a mandatory document or declaration is missing. Let's find what's pending before the deadline.",
            [
                "Note the bid number and the submission deadline.",
                "Ask the caller to open the bid checklist and read any items marked incomplete.",
                "Confirm all mandatory documents are PDF files under 10 MB each.",
                "Ask them to accept the declarations on the final page.",
                "If the deadline is within one hour and the button is still disabled, escalate immediately.",
            ],
            ["Bid number", "Screenshot of the checklist"],
            ["submit button greyed out on bid", "can't submit my bid and deadline is today"],
        ),
        (
            "reverse_auction_not_visible",
            "Reverse auction not visible to seller",
            ["reverse auction", "auction not visible", "ra not showing", "not invited to auction", "auction missing"],
            "Only sellers who qualified in the technical round are invited to the reverse auction. Let me check your status.",
            [
                "Note the bid number linked to the auction.",
                "Check whether the seller qualified in the technical evaluation.",
                "If qualified, ask the caller to check Bids > Auctions and refresh after the start time.",
                "If not qualified, explain the evaluation result and where to view remarks.",
            ],
            ["Bid number"],
            ["reverse auction is not showing in my account", "why can't I see the auction for my bid"],
        ),
        (
            "bid_disqualified_technical_evaluation",
            "Bid disqualified in technical evaluation",
            ["bid disqualified", "technical evaluation", "rejected bid", "not qualified", "evaluation remarks"],
            "I'm sorry your bid was disqualified. The evaluation remarks explain why, and you may be able to raise a representation.",
            [
                "Ask the caller to open the bid and read the evaluation remarks.",
                "Explain that representations can be raised within 48 hours of the result.",
                "Guide them to Bids > Representation and attach supporting documents.",
                "Set expectations that the buyer reviews representations, not the support team.",
            ],
            ["Evaluation remarks screenshot", "Supporting documents for representation"],
            ["my bid got rejected in technical round", "how to contest bid disqualification"],
        ),
    ],
    "orders_delivery": [
        (
            "order_not_appearing_in_dashboard",
            "Order not appearing in seller dashboard",
            ["order not showing", "missing order", "order dashboard", "new order not visible", "purchase order missing"],
            "Orders appear in the dashboard within 15 minutes of the buyer confirming. Let's find yours.",
            [
                "Ask for the order number the buyer shared.",
                "Ask the caller to search by order number under Orders > All orders.",
                "Check that the date filter includes the order date.",
                "If a sub-user is logged in, confirm they have order access.",
                "Escalate with the order number if it still doesn't appear.",
            ],
            ["Order number"],
            ["buyer says they placed an order but I don't see it", "purchase order missing from my dashboard"],
        ),
        (
            "request_delivery_extension",
            "Request delivery date extension",
            ["delivery extension", "extend delivery", "delay delivery", "more time to deliver", "revised delivery date"],
            "You can request a delivery extension from the order page; the buyer approves or rejects it.",
            [
                "Ask the caller to open the order and choose 'Request extension'.",
                "Have them enter a new date and a clear reason.",
                "Explain that late delivery penalties may apply if the buyer rejects the request.",
                "Advise them to request the extension before the original date passes.",
            ],
            ["Order number", "Reason for delay"],
            ["need more days to deliver the order", "how to ask buyer for delivery date extension"],
        ),
        (
            "order_cancelled_by_buyer",
            "Order cancelled by buyer",
            ["order cancelled", "buyer cancelled", "cancellation", "order withdrawn", "cancelled after dispatch"],
            "Buyers can cancel before dispatch. If you had already shipped, we can help you raise a claim.",
            [
                "Check whether the order was cancelled before or after dispatch.",
                "If before dispatch, explain no further action is needed.",
                "If after dispatch, ask for the shipment tracking number.",
                "Guide the caller to raise a cancellation claim with the tracking proof.",
            ],
            ["Order number", "Shipment tracking proof"],
            ["buyer cancelled my order after I shipped it", "order got cancelled what happens now"],
        ),
    ],
    "invoices_payments": [
        (
            "invoice_generation_failed",
            "Invoice generation failed",
            ["invoice failed", "cannot generate invoice", "invoice error", "bill not generated", "invoice button"],
            "Invoices can only be generated after the buyer confirms receipt. Let's check the order status.",
            [
                "Ask for the order number.",
                "Check whether the buyer has generated the goods receipt.",
                "If not, explain that the invoice unlocks after receipt confirmation.",
                "If receipt is confirmed, ask the caller to retry and note any error code.",
                "Escalate with the error code if generation still fails.",
            ],
            ["Order number", "Error code screenshot"],
            ["unable to create invoice for my order", "invoice generation is showing error"],
        ),
        (
            "payment_delayed_after_delivery",
            "Payment delayed after delivery",
            ["payment delayed", "payment not received", "pending payment", "late payment", "money not credited"],
            "Buyers have 10 days after receipt to pay. Let me check where the payment is in that cycle.",
            [
                "Ask for the order number and invoice date.",
                "Check whether the buyer has confirmed receipt and approved the invoice.",
                "If within 10 days of receipt, explain the payment timeline.",
                "If overdue, raise a payment follow-up to the buyer organisation.",
                "Escalate if the follow-up is unanswered after three business days.",
            ],
            ["Order number", "Invoice copy"],
            ["delivered the goods but still not paid", "payment for my order is pending for weeks"],
        ),
        (
            "tax_amount_mismatch_on_invoice",
            "Tax amount mismatch on invoice",
            ["tax mismatch", "wrong tax", "tax amount", "invoice tax error", "tax calculation"],
            "Tax is calculated from the product's tax category at order time. Let's compare that with your invoice.",
            [
                "Ask for the order number and the tax rate the caller expected.",
                "Check the tax category saved on the listing at order time.",
                "If the listing category was wrong, guide the caller to issue a credit note and corrected invoice.",
                "Remind them to fix the listing so future orders are correct.",
            ],
            ["Order number", "Invoice copy"],
            ["tax on invoice is calculated wrong", "invoice shows different tax amount"],
        ),
    ],
    "shipping_logistics": [
        (
            "courier_pickup_missed",
            "Courier missed the scheduled pickup",
            ["pickup missed", "courier did not come", "pickup not done", "reschedule pickup", "shipment not collected"],
            "Missed pickups happen when the courier slot was full. We can rebook it and protect your dispatch date.",
            [
                "Ask for the order number and the pickup slot that was booked.",
                "Check the courier's pickup status and any 'attempted' note.",
                "Rebook the pickup for the next available slot from the shipment page.",
                "If the dispatch deadline is today, mark the order 'pickup delayed by courier' so no penalty applies.",
                "Escalate if the courier misses the rebooked slot.",
            ],
            ["Order number", "Pickup booking reference"],
            ["the delivery guy never came to collect the parcel", "pickup was booked for today but nobody showed up"],
        ),
        (
            "shipping_label_not_generating",
            "Shipping label will not generate",
            ["shipping label", "label error", "cannot print label", "airway bill", "label download failed"],
            "Labels fail when the package weight or dimensions are missing. Let's check the shipment form.",
            [
                "Ask the caller to open the shipment form for the order.",
                "Confirm package weight and all three dimensions are filled in.",
                "Check that the pickup address has a valid postcode.",
                "Ask them to regenerate the label and download the PDF.",
            ],
            ["Order number", "Package weight and dimensions"],
            ["can't print the label for my shipment", "label button gives an error"],
        ),
        (
            "delivery_address_undeliverable",
            "Courier says delivery address is undeliverable",
            ["undeliverable address", "address not found", "delivery failed", "return to origin", "courier cannot locate"],
            "When the courier can't find the address, we confirm it with the buyer before the parcel is sent back.",
            [
                "Ask for the order number and the courier's failure reason.",
                "Contact the buyer's consignee through the order messages to confirm the address and a phone number.",
                "Share the corrected details with the courier from the shipment page.",
                "If the buyer doesn't reply in 48 hours, let the shipment return and inform the buyer.",
            ],
            ["Order number", "Courier failure note"],
            ["courier says they can't find the buyer's address", "delivery failed because address is wrong"],
        ),
    ],
    "sub_users": [
        (
            "add_sub_user",
            "Add a sub-user to seller account",
            ["add user", "sub user", "new employee login", "create user", "team member access"],
            "Admins can add sub-users and give them limited roles, so your team can work without sharing passwords.",
            [
                "Confirm the caller is the account admin.",
                "Guide them to Settings > Users > Add user.",
                "Have them choose a role such as Catalogue, Bids or Finance.",
                "Explain that the new user receives an activation email.",
            ],
            ["New user's work email"],
            ["how can my staff get their own login", "add another user to our seller account"],
        ),
        (
            "sub_user_cannot_access_bids",
            "Sub-user cannot access bids",
            ["sub user access", "permission denied", "cannot see bids", "role permissions", "access denied"],
            "When a sub-user can't see a section, it's almost always their role. The admin can adjust it.",
            [
                "Ask which section the sub-user cannot open.",
                "Ask the admin to open Settings > Users and check that user's role.",
                "Add the Bids permission or change the role.",
                "Ask the sub-user to sign out and back in.",
            ],
            ["Sub-user's login email"],
            ["my colleague cannot open the bids page", "sub user gets access denied"],
        ),
        (
            "transfer_admin_role",
            "Transfer admin role to another user",
            ["transfer admin", "change admin", "admin left company", "primary user", "owner change"],
            "Transferring admin rights protects your account when people change roles. It needs confirmation from the business.",
            [
                "If the current admin is available, they can transfer the role from Settings > Users.",
                "If the admin has left, collect an authorisation letter from the business.",
                "The new admin must complete identity verification.",
                "Escalate letter-based transfers for manual approval.",
            ],
            ["Authorisation letter", "Identity proof of the new admin"],
            ["our admin left the company, need to change admin", "how to make someone else the main user"],
        ),
    ],
    "disputes_returns": [
        (
            "buyer_raised_quality_dispute",
            "Buyer raised a quality dispute",
            ["quality dispute", "buyer complaint", "defective goods", "dispute raised", "product quality"],
            "When a buyer raises a quality dispute, you get seven days to respond with evidence.",
            [
                "Ask for the dispute ID.",
                "Explain the seven-day response window.",
                "Guide the caller to respond with photos, test reports or replacement offers.",
                "Explain that the dispute cell decides if both sides cannot agree.",
            ],
            ["Dispute ID", "Inspection photos or test reports"],
            ["buyer complained about product quality", "how do I respond to a quality dispute"],
        ),
        (
            "return_pickup_not_scheduled",
            "Return pickup not scheduled",
            ["return pickup", "return not collected", "reverse pickup", "return shipment", "pickup pending"],
            "Return pickups are scheduled by the seller within three days of the return being approved.",
            [
                "Ask for the return ID.",
                "Check whether the return was approved.",
                "Guide the seller to schedule pickup from the return page.",
                "If the courier missed the pickup, ask them to reschedule and share the courier reference.",
            ],
            ["Return ID", "Courier reference"],
            ["return items have not been picked up", "reverse pickup is still pending"],
        ),
        (
            "penalty_applied_incorrectly",
            "Penalty applied incorrectly",
            ["penalty", "late delivery penalty", "deduction", "wrong penalty", "penalty waiver"],
            "Penalties are applied automatically for late delivery. If the delay wasn't yours, you can request a waiver.",
            [
                "Ask for the order number and the penalty amount.",
                "Check whether an extension was approved for the order.",
                "If an approved extension exists, raise a waiver request with the approval reference.",
                "If the buyer caused the delay, collect evidence and raise a waiver request.",
            ],
            ["Order number", "Extension approval or delay evidence"],
            ["penalty deducted even though delivery was on time", "how to get a late delivery penalty removed"],
        ),
    ],
}

# ---------------------------------------------------------------------------
# Buyer side
# ---------------------------------------------------------------------------

BUYER_CATEGORIES = [
    ("org_onboarding", "Organisation Onboarding", "Buyer Onboarding Desk", "Onboarding Specialist (Tier 2)"),
    ("login_otp", "Login & OTP", "Access Support Team", "Identity Support Analyst"),
    ("buyer_users", "Users & Roles", "Access Support Team", "Account Administration Analyst"),
    ("direct_purchase", "Direct Purchase", "Buyer Success Team", "Purchasing Advisor"),
    ("bids_rfq", "Bids & RFQs", "Sourcing Events Desk", "Sourcing Event Specialist"),
    ("orders_delivery", "Orders & Delivery", "Order Operations Team", "Fulfilment Coordinator"),
    ("receiving_inspection", "Receiving & Inspection", "Order Operations Team", "Receiving Support Analyst"),
    ("payments_invoices", "Payments & Invoices", "Buyer Finance Desk", "Payments Analyst"),
    ("disputes_feedback", "Disputes & Feedback", "Dispute Resolution Cell", "Dispute Case Manager"),
    ("account_closure", "Account Closure", "Buyer Onboarding Desk", "Account Lifecycle Analyst"),
]

BUYER_BRANCHES = {
    "org_onboarding": [
        (
            "register_new_buyer_organisation",
            "Register a new buyer organisation",
            ["register organisation", "new buyer account", "onboard department", "buyer signup", "create organisation"],
            "Organisations register once, then add their purchasing staff as users. I'll walk you through it.",
            [
                "Ask the caller for the organisation's legal name and official email domain.",
                "Guide them to 'Register as buyer' and complete the organisation form.",
                "Explain that an approving officer must be nominated during registration.",
                "Tell them approval takes up to two business days.",
            ],
            ["Organisation registration certificate", "Nomination of approving officer"],
            ["how does our department register as a buyer", "new organisation buyer registration steps"],
        ),
        (
            "approving_officer_not_assigned",
            "Approving officer not assigned",
            ["approving officer", "approver missing", "no approver", "purchase approval", "approval hierarchy"],
            "Purchases above the direct-buy limit need an approving officer. Let's assign one.",
            [
                "Confirm the caller is the organisation admin.",
                "Guide them to Organisation > Approval hierarchy.",
                "Have them select an existing user as approving officer or invite a new one.",
                "Explain that pending purchases resume once the officer accepts.",
            ],
            ["Approving officer's work email"],
            ["it says no approving officer for our account", "how to set who approves purchases"],
        ),
        (
            "organisation_details_incorrect",
            "Organisation details are incorrect",
            ["wrong organisation name", "update organisation details", "organisation address", "department name wrong", "edit organisation"],
            "Organisation details can be corrected by the admin, with a supporting letter for name changes.",
            [
                "Ask which field is incorrect.",
                "For address or contact changes, guide the admin to Organisation > Details.",
                "For name changes, collect an official letter on letterhead.",
                "Explain that name changes are reviewed within two business days.",
            ],
            ["Official letter for name changes"],
            ["our department name is spelled wrong", "need to correct organisation details"],
        ),
    ],
    "login_otp": [
        (
            "buyer_otp_not_received",
            "Buyer OTP not received",
            ["otp not received", "login otp", "sms code missing", "verification code", "no otp"],
            "Let's get your login code through. Delays usually come from SMS filtering or an outdated number.",
            [
                "Confirm the last four digits of the registered mobile number.",
                "Ask the caller to wait 60 seconds before pressing 'Resend OTP' once.",
                "Offer the email OTP option if available.",
                "If the number is outdated, start the mobile update process with the organisation admin.",
            ],
            ["Registered mobile number"],
            ["buyer login code is not coming", "not receiving otp for buyer account"],
        ),
        (
            "buyer_account_locked",
            "Buyer account locked",
            ["account locked", "too many attempts", "locked out", "login disabled", "blocked account"],
            "Accounts lock for 30 minutes after five failed attempts. I can help you reset safely.",
            [
                "Tell the caller how long remains on the lock.",
                "Recommend a password reset once the lock lifts.",
                "If urgent, verify identity with the organisation admin and raise an unlock request.",
            ],
            ["Organisation admin confirmation"],
            ["buyer account says locked", "locked out of purchasing account"],
        ),
        (
            "update_registered_mobile_number",
            "Update registered mobile number",
            ["change mobile number", "update phone", "new mobile", "old number", "mobile update"],
            "Mobile numbers are updated by verifying both the email and the new number.",
            [
                "Ask the caller to open Profile > Contact details.",
                "Have them verify the change with an email OTP.",
                "Then verify the new number with an SMS OTP.",
                "If they can't access the email, the organisation admin must approve the change.",
            ],
            ["Access to registered email"],
            ["my phone number changed, how to update", "need to change the mobile linked to my login"],
        ),
    ],
    "buyer_users": [
        (
            "create_buyer_user",
            "Create a new buyer user",
            ["add buyer user", "new purchaser", "create user", "add staff", "user creation"],
            "Organisation admins can add buyers and assign purchase limits per user.",
            [
                "Confirm the caller is the organisation admin.",
                "Guide them to Organisation > Users > Add user.",
                "Have them set the role and the per-order purchase limit.",
                "Explain that the new user activates from the invitation email.",
            ],
            ["New user's work email"],
            ["how to add another purchaser in our organisation", "create login for new buyer staff"],
        ),
        (
            "deactivate_departed_user",
            "Deactivate a user who left",
            ["deactivate user", "employee left", "remove user", "disable login", "transferred officer"],
            "Deactivating departed users keeps your organisation's purchases secure. Their open orders can be reassigned.",
            [
                "Ask the admin to open Organisation > Users and select the user.",
                "Choose 'Deactivate' and reassign their open orders to another buyer.",
                "Explain that order history stays available for audits.",
            ],
            ["Name of the user to deactivate"],
            ["officer transferred, remove his login", "how to disable an old buyer user"],
        ),
        (
            "change_buyer_role_permissions",
            "Change buyer role or permissions",
            ["change role", "permissions", "purchase limit", "upgrade access", "role update"],
            "Roles and purchase limits are set by the organisation admin and take effect on next login.",
            [
                "Ask which permission or limit needs to change.",
                "Guide the admin to Organisation > Users > Edit role.",
                "Explain that limits above the organisation cap need approving officer sign-off.",
                "Ask the user to sign out and back in.",
            ],
            ["Approving officer sign-off for higher limits"],
            ["need higher purchase limit for my user", "how to change a buyer's permissions"],
        ),
    ],
    "direct_purchase": [
        (
            "price_changed_in_cart",
            "Price changed after adding to cart",
            ["price changed", "cart price", "price increased", "price difference", "updated price"],
            "Prices in the cart refresh from the seller's live listing. Let's check what changed.",
            [
                "Ask the caller to open the cart and read the 'price updated' notice.",
                "Explain that sellers can change prices until checkout.",
                "Suggest comparing with similar listings before confirming.",
                "If the price changed after checkout, collect the order number and escalate.",
            ],
            ["Order number, if already placed"],
            ["the price went up after I added it to cart", "cart is showing a different price now"],
        ),
        (
            "direct_purchase_limit_exceeded",
            "Direct purchase limit exceeded",
            ["purchase limit", "limit exceeded", "cannot buy directly", "above limit", "direct buy cap"],
            "Direct purchases have a value cap. Above it, you'll need approval or a bid.",
            [
                "Ask for the cart value and the caller's purchase limit.",
                "If under the organisation cap, request approval from the approving officer.",
                "If above the organisation cap, explain that a bid or RFQ is required.",
            ],
            ["Cart value", "Approving officer details"],
            ["it says I exceeded the direct purchase limit", "cannot place order above my limit"],
        ),
        (
            "compare_products_before_purchase",
            "Compare products before purchase",
            ["compare products", "lowest price", "comparison", "best offer", "choose seller"],
            "The comparison view shows up to four listings side by side, so you can choose the best value.",
            [
                "Ask the caller to tick 'Compare' on up to four listings.",
                "Explain the columns: price, delivery time, seller rating and warranty.",
                "Remind them to record the reason if they don't choose the lowest price.",
            ],
            ["Purchase justification note"],
            ["how do I compare two products", "want to see sellers side by side before buying"],
        ),
    ],
    "bids_rfq": [
        (
            "create_rfq",
            "Create a request for quotation",
            ["create rfq", "request for quotation", "new bid", "publish rfq", "tender creation"],
            "An RFQ invites sellers to quote for your requirement. I'll guide you through publishing one.",
            [
                "Guide the caller to Sourcing > Create RFQ.",
                "Have them enter specifications, quantity and delivery location.",
                "Ask them to set a bid deadline at least seven days away.",
                "Explain that the approving officer must approve before publishing.",
            ],
            ["Specification document", "Approval from approving officer"],
            ["how to float an rfq", "steps to create a new quotation request"],
        ),
        (
            "extend_bid_deadline",
            "Extend bid deadline",
            ["extend deadline", "bid extension", "more time for bids", "deadline change", "corrigendum"],
            "You can extend a bid deadline before it closes; sellers are notified automatically.",
            [
                "Ask for the bid number.",
                "Check that the deadline hasn't passed.",
                "Guide the caller to Bid > Amend > Extend deadline.",
                "Explain that a reason is recorded and visible to sellers.",
            ],
            ["Bid number", "Reason for extension"],
            ["need to give sellers more time on my bid", "how to extend rfq closing date"],
        ),
        (
            "technical_evaluation_upload_failed",
            "Technical evaluation upload failed",
            ["technical evaluation", "evaluation upload", "evaluation sheet", "cannot upload evaluation", "evaluation error"],
            "Evaluation results must be uploaded in the provided template. Let's check the file.",
            [
                "Ask for the bid number and the error message.",
                "Confirm the file uses the latest evaluation template.",
                "Check that every participating seller has a qualified or disqualified status with remarks.",
                "Ask the caller to retry the upload.",
            ],
            ["Bid number", "Evaluation sheet"],
            ["evaluation result is not uploading", "technical evaluation file shows error"],
        ),
    ],
    "orders_delivery": [
        (
            "order_status_not_updated",
            "Order status not updated",
            ["order status", "status not updating", "order stuck", "tracking not updated", "shipment status"],
            "Order status updates when the seller records dispatch. Let's check the latest event.",
            [
                "Ask for the order number.",
                "Check the last status event and its timestamp.",
                "If the seller hasn't marked dispatch, send a reminder to the seller.",
                "If dispatched, share the tracking link with the caller.",
            ],
            ["Order number"],
            ["order still shows placed after a week", "status of my order is not changing"],
        ),
        (
            "change_consignee_after_order",
            "Change consignee after ordering",
            ["change consignee", "delivery address", "receiving officer", "change delivery location", "consignee update"],
            "The consignee can be changed before dispatch, with the seller's agreement.",
            [
                "Ask for the order number and the new consignee details.",
                "Check that the order hasn't been dispatched.",
                "Guide the caller to Order > Request consignee change.",
                "Explain that the seller must accept the change.",
            ],
            ["Order number", "New consignee details"],
            ["need to change who receives the delivery", "update delivery location after placing order"],
        ),
        (
            "delivery_overdue",
            "Delivery overdue",
            ["delivery late", "overdue delivery", "not delivered", "delayed shipment", "past delivery date"],
            "If delivery is overdue, you can follow up with the seller and penalties apply automatically.",
            [
                "Ask for the order number and the promised delivery date.",
                "Check whether the seller requested an extension.",
                "If not, send a delivery follow-up to the seller.",
                "Explain how late delivery penalties are calculated.",
            ],
            ["Order number"],
            ["my delivery is late", "seller has not delivered past the due date"],
        ),
    ],
    "receiving_inspection": [
        (
            "generate_goods_receipt",
            "Generate goods receipt",
            ["goods receipt", "receipt note", "confirm delivery", "generate receipt", "acceptance"],
            "Generating the goods receipt confirms delivery and starts the seller's payment cycle.",
            [
                "Ask the caller to open the order and choose 'Generate receipt'.",
                "Have them enter quantity received and inspection result.",
                "Explain that the receipt must be generated within 10 days of delivery.",
            ],
            ["Order number", "Inspection result"],
            ["how do I confirm I received the goods", "steps to create the receipt note"],
        ),
        (
            "reject_damaged_goods",
            "Reject damaged goods",
            ["damaged goods", "reject delivery", "broken items", "quality rejection", "defective items"],
            "You can reject damaged items during receipt; the seller is asked to replace them.",
            [
                "Ask the caller to record the damage with photos.",
                "During receipt, mark the affected quantity as rejected with a reason.",
                "Explain that the seller has seven days to replace the items.",
            ],
            ["Photos of damage", "Order number"],
            ["items arrived broken, how to reject", "received damaged products"],
        ),
        (
            "partial_delivery_receipt",
            "Partial delivery receipt",
            ["partial delivery", "short delivery", "quantity less", "partial receipt", "remaining items"],
            "For partial deliveries, receipt the quantity you received; the rest stays open.",
            [
                "Ask how many units were received against the order quantity.",
                "Guide the caller to receipt only the received quantity.",
                "Explain that the balance remains open for the seller to deliver.",
            ],
            ["Order number", "Delivery challan"],
            ["seller delivered only half the quantity", "how to receipt a partial delivery"],
        ),
    ],
    "payments_invoices": [
        (
            "payment_not_processed_after_receipt",
            "Payment not processed after receipt",
            ["payment not processed", "payment pending", "seller not paid", "payment stuck", "release payment"],
            "After receipt, the invoice must be approved before payment releases. Let's find which step is pending.",
            [
                "Ask for the order number.",
                "Check whether the invoice was approved by the finance user.",
                "If not approved, guide the finance user to Payments > Pending invoices.",
                "If approved, check the payment batch status and share the reference.",
            ],
            ["Order number", "Invoice number"],
            ["seller says payment not received though we approved", "payment stuck after goods receipt"],
        ),
        (
            "invoice_missing_for_order",
            "Invoice missing for order",
            ["invoice missing", "no invoice", "cannot find invoice", "bill not uploaded", "invoice not available"],
            "Sellers upload the invoice after your goods receipt. If it's missing, we can nudge the seller.",
            [
                "Ask for the order number.",
                "Confirm the goods receipt was generated.",
                "If yes, send an invoice reminder to the seller.",
                "Explain that payment can't start until the invoice is uploaded.",
            ],
            ["Order number"],
            ["there is no invoice on my order", "seller hasn't uploaded the bill"],
        ),
        (
            "corporate_card_declined_at_checkout",
            "Corporate card declined at checkout",
            ["card declined", "payment card", "checkout payment failed", "credit card rejected", "card not accepted"],
            "Card payments are declined by the issuing bank, not by us. Let's check the usual causes before trying again.",
            [
                "Ask for the decline message shown at checkout.",
                "Check whether the order total exceeds the card's per-transaction limit.",
                "Ask the caller to confirm the card is enabled for online purchases.",
                "Offer invoice-based payment if the organisation has it enabled.",
            ],
            ["Decline message screenshot"],
            ["my company card keeps getting declined", "checkout fails when paying by card"],
        ),
    ],
    "disputes_feedback": [
        (
            "raise_dispute_against_seller",
            "Raise a dispute against a seller",
            ["raise dispute", "complaint against seller", "seller issue", "file complaint", "dispute"],
            "You can raise a dispute from the order page; the seller gets seven days to respond.",
            [
                "Ask for the order number and the nature of the issue.",
                "Guide the caller to Order > Raise dispute.",
                "Have them attach evidence such as photos or reports.",
                "Explain the seven-day seller response window.",
            ],
            ["Order number", "Evidence of the issue"],
            ["how to complain about a seller", "want to raise a dispute for my order"],
        ),
        (
            "rate_seller_after_delivery",
            "Rate a seller after delivery",
            ["rate seller", "seller rating", "feedback", "review seller", "performance rating"],
            "Seller ratings help other buyers. You can rate after the goods receipt.",
            [
                "Ask the caller to open the completed order.",
                "Guide them to 'Rate seller' and score delivery, quality and communication.",
                "Explain that ratings can be edited within 30 days.",
            ],
            ["Order number"],
            ["where can I give rating to the seller", "how to leave seller feedback"],
        ),
        (
            "escalate_unresolved_complaint",
            "Escalate an unresolved complaint",
            ["escalate complaint", "unresolved", "no response", "complaint pending", "escalation"],
            "If your complaint hasn't been resolved in time, I can escalate it to the dispute cell.",
            [
                "Ask for the dispute ID.",
                "Check how long the dispute has been open.",
                "If past the response window, escalate to the dispute cell.",
                "Share the escalation reference with the caller.",
            ],
            ["Dispute ID"],
            ["my complaint is pending for weeks", "nobody is resolving my dispute"],
        ),
    ],
    "account_closure": [
        (
            "close_buyer_account",
            "Close a buyer account",
            ["close account", "delete account", "deactivate organisation", "account closure", "remove buyer account"],
            "Accounts can be closed once there are no open orders, bids or payments.",
            [
                "Check for open orders, active bids and pending payments.",
                "Ask the organisation admin to submit a closure request with a letter.",
                "Explain that records are retained for audit after closure.",
            ],
            ["Closure request letter"],
            ["we want to close our buyer account", "how to delete organisation account"],
        ),
        (
            "transfer_pending_orders_before_closure",
            "Transfer pending orders before closure",
            ["transfer orders", "pending orders", "reassign orders", "handover", "orders before closing"],
            "Before closing, open orders must be completed or moved to another active buyer.",
            [
                "List the open orders with the caller.",
                "Guide the admin to reassign each order to an active buyer.",
                "Confirm no orders remain before submitting closure.",
            ],
            ["List of open orders"],
            ["how to move open orders before closing account", "reassign orders to another officer"],
        ),
        (
            "reactivate_closed_account",
            "Reactivate a closed account",
            ["reactivate", "reopen account", "closed by mistake", "restore account", "account reactivation"],
            "Closed accounts can be reactivated within 90 days with a request from the organisation.",
            [
                "Check when the account was closed.",
                "If within 90 days, collect a reactivation letter from the organisation.",
                "If older than 90 days, explain that a fresh registration is required.",
            ],
            ["Reactivation request letter"],
            ["our account was closed by mistake", "can we reopen the old buyer account"],
        ),
    ],
}

# Synonym groups used by query expansion. Generic procurement vocabulary only.
SYNONYM_GROUPS = {
    "seller": [
        ["otp", "one time password", "login code", "sms code", "verification code"],
        ["listing", "product", "item", "catalogue", "catalog"],
        ["visible", "showing", "appear", "listed", "display"],
        ["bid", "tender", "rfq", "quotation"],
        ["reverse auction", "auction", "ra"],
        ["invoice", "bill"],
        ["payout", "payment", "settlement", "money"],
        ["courier", "shipping", "logistics", "pickup"],
        ["rejected", "declined", "not accepted", "failed"],
        ["sub user", "team member", "staff login", "user"],
        ["dispute", "complaint", "grievance"],
        ["bank account", "bank details", "payout account"],
    ],
    "buyer": [
        ["otp", "one time password", "login code", "sms code", "verification code"],
        ["rfq", "request for quotation", "bid", "tender"],
        ["goods receipt", "receipt note", "grn", "acceptance"],
        ["consignee", "receiving officer", "delivery location"],
        ["invoice", "bill"],
        ["payment", "release payment", "settle"],
        ["dispute", "complaint", "grievance"],
        ["user", "purchaser", "buyer user", "staff"],
        ["close account", "delete account", "deactivate"],
        ["card", "payment card", "credit card"],
    ],
}

ABBREVIATIONS = {
    "otp": "otp",
    "rfq": "request for quotation",
    "grn": "goods receipt",
    "po": "purchase order",
    "kyc": "kyc",
    "pwd": "password",
    "acct": "account",
    "inv": "invoice",
    "awb": "airway bill",
    "ra": "reverse auction",
}

TYPO_PHRASES = {
    "listng missing": "listing missing",
    "pasword reset": "password reset",
    "invoce not generated": "invoice not generated",
    "shiping label": "shipping label",
    "reverse aution": "reverse auction",
    "goods reciept": "goods receipt",
}

PROTECTED_PHRASES = ["northwind", "reverse auction", "goods receipt", "request for quotation"]

# FAQ-style knowledge (self-service help articles), separate from agent branches.
# (user_type, category_name, question, short_answer, steps, search_phrases)
FAQ = [
    ("Seller", "Seller Registration", "Which documents do I need to register as a seller?", "Keep your tax certificate, business registration proof and a cancelled cheque ready.", ["Tax registration certificate", "Business registration proof", "Cancelled cheque for payouts"], ["seller documents", "registration checklist"]),
    ("Seller", "Seller Registration", "How long does seller registration take?", "Most applications are reviewed within three business days.", ["Submit all documents", "Track status on the dashboard", "Respond quickly to any document requests"], ["registration time", "approval time"]),
    ("Seller", "Login & OTP", "Can I receive my login code by email instead of SMS?", "Yes, if your email is verified you can choose the email option on the code screen.", ["Click 'Use email instead'", "Enter the code from your inbox"], ["email otp", "otp by email"]),
    ("Seller", "Login & OTP", "What are the password rules?", "Passwords need at least 12 characters, including a number and a symbol.", ["Use 12 or more characters", "Include a number and a symbol", "Avoid reusing old passwords"], ["password policy", "password requirements"]),
    ("Seller", "Profile & KYC", "Which file formats are accepted for KYC documents?", "Upload PDF, JPG or PNG files up to 5 MB each.", ["Scan in colour at 300 dpi", "Keep each file under 5 MB"], ["kyc format", "document size"]),
    ("Seller", "Bank Account & Payouts", "When are payouts made?", "Payouts run every weekday for invoices approved by the previous day.", ["Invoice approved by buyer", "Payout batch runs next weekday", "Funds arrive in 1-2 days"], ["payout schedule", "settlement timing"]),
    ("Seller", "Catalogue & Listings", "What image size is required for product photos?", "Use at least 800x800 pixels on a plain white background.", ["Minimum 800x800 pixels", "Plain white background", "No watermarks"], ["image guidelines", "photo size"]),
    ("Seller", "Catalogue & Listings", "How many products can I upload in one bulk file?", "Up to 500 rows per bulk upload file.", ["Download the latest template", "Keep to 500 rows", "Fix rows listed in the error report"], ["bulk limit", "upload rows"]),
    ("Seller", "Brand Authorisation", "How do I prove I own a brand?", "Upload a trademark certificate or registration application in your business name.", ["Trademark certificate", "Or pending trademark application"], ["brand proof", "trademark"]),
    ("Seller", "Bids & Reverse Auctions", "What file size limits apply to bid documents?", "Each bid document must be a PDF under 10 MB.", ["Convert to PDF", "Compress large scans", "Upload before the deadline"], ["bid document size", "bid upload limit"]),
    ("Seller", "Bids & Reverse Auctions", "How does a reverse auction work?", "Qualified sellers lower their prices in real time; the lowest valid price at close wins.", ["Qualify in the technical round", "Join at the start time", "Submit decrements before close"], ["reverse auction rules", "auction process"]),
    ("Seller", "Orders & Delivery", "Can I partially deliver an order?", "Yes, unless the buyer disabled partial delivery; each delivery is receipted separately.", ["Check the order's delivery terms", "Dispatch available quantity", "Record each dispatch"], ["partial dispatch", "split delivery"]),
    ("Seller", "Invoices & Payments", "When can I raise an invoice?", "After the buyer generates the goods receipt for the delivery.", ["Wait for goods receipt", "Generate invoice from the order", "Attach supporting documents"], ["invoice timing", "raise bill"]),
    ("Seller", "Shipping & Logistics", "Who pays for return shipping?", "The party at fault pays: the seller for wrong or damaged items, the buyer for change-of-mind returns.", ["Check the return reason", "Generate the return label", "Track the return to delivery"], ["return shipping cost", "return label"]),
    ("Seller", "Sub-users & Roles", "What roles can I give to sub-users?", "Catalogue, Bids, Orders and Finance roles can be combined per user.", ["Catalogue", "Bids", "Orders", "Finance"], ["user roles", "permissions"]),
    ("Seller", "Disputes & Returns", "How long do I have to respond to a dispute?", "Seven calendar days from when the dispute is raised.", ["Open the dispute", "Upload evidence", "Propose a resolution"], ["dispute timeline", "respond to complaint"]),
    ("Buyer", "Organisation Onboarding", "Who can register an organisation as a buyer?", "Any authorised officer with an official email address on the organisation's domain.", ["Use an official email", "Nominate an approving officer", "Upload the registration certificate"], ["buyer eligibility", "organisation registration"]),
    ("Buyer", "Login & OTP", "Can two people share one buyer login?", "No. Each person needs their own user so purchases are traceable.", ["Ask your admin to add a user", "Never share passwords"], ["shared login", "multiple users"]),
    ("Buyer", "Users & Roles", "How are purchase limits set?", "Admins set a per-order limit for each user, up to the organisation cap.", ["Open Users", "Edit purchase limit", "Higher limits need approving officer sign-off"], ["purchase limit", "spending limit"]),
    ("Buyer", "Direct Purchase", "What is the direct purchase limit?", "Orders up to the organisation's direct-buy cap can be placed without a bid.", ["Check your organisation cap", "Above it, create an RFQ"], ["direct buy cap", "purchase without bid"]),
    ("Buyer", "Direct Purchase", "Do I have to buy the cheapest product?", "Not always, but you must record a justification when you don't.", ["Compare listings", "Record justification", "Proceed to checkout"], ["lowest price rule", "justification"]),
    ("Buyer", "Bids & RFQs", "What is the minimum bid duration?", "RFQs must stay open for at least seven days.", ["Set deadline seven or more days ahead", "Extend if fewer than three sellers respond"], ["bid duration", "rfq timeline"]),
    ("Buyer", "Orders & Delivery", "How do I track a delivery?", "Open the order to see dispatch events and the courier tracking link.", ["Open the order", "View status timeline", "Click the tracking link"], ["track order", "shipment tracking"]),
    ("Buyer", "Receiving & Inspection", "How long do I have to generate a goods receipt?", "Within 10 days of delivery, otherwise the order is auto-escalated.", ["Inspect the goods", "Generate receipt within 10 days"], ["receipt deadline", "grn timeline"]),
    ("Buyer", "Payments & Invoices", "How long do we have to pay the seller?", "Payment is due within 10 days of goods receipt.", ["Approve invoice", "Release payment batch", "Share payment reference"], ["payment terms", "due date"]),
    ("Buyer", "Disputes & Feedback", "Can I edit a seller rating?", "Yes, within 30 days of submitting it.", ["Open the completed order", "Edit rating", "Save"], ["change rating", "edit feedback"]),
    ("Buyer", "Account Closure", "What happens to records after closing an account?", "Order and payment records are kept for audit for seven years.", ["Records retained", "Read-only access on request"], ["data retention", "closed account records"]),
]

# Supervisor-queue demo items: realistic unresolved questions (no matching branch).
DEMO_PENDING_QUERIES = [
    ("seller", "warehouse address change for one product only"),
    ("seller", "buyer asking for installation certificate after delivery"),
    ("buyer", "how to split one order across two cost centres"),
    ("buyer", "seller sent extra quantity, how to receipt"),
]
